FROM recordexpungpdx/recordexpungpdx:expungeservicebase

RUN python3.7 -m pip install pipenv
RUN mkdir -p /var/www/expungeservice
RUN mkdir /var/www/logs/

COPY ./Pipfile ./Pipfile.lock ./setup.py /var/www/expungeservice/
WORKDIR /var/www/expungeservice
RUN pipenv install --system --deploy &&\
    python3.7 -m setup install
COPY . /var/www/expungeservice


WORKDIR /var/www
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
CMD ["uwsgi", "--py-autoreload", "1",  "--http", "0.0.0.0:5000", "--module", "expungeservice.wsgi"]
