FROM recordexpungpdx/recordexpungpdx:expungeservicebase

RUN mkdir -p /var/www/expungeservice
COPY . /var/www/expungeservice
WORKDIR /var/www/expungeservice
RUN python3.7 -m pip install -r requirements.txt && rm requirements.txt &&\
    python3.7 -m setup install


WORKDIR /var/www
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

CMD uwsgi --http-socket 0.0.0.0:$PORT --module expungeservice.wsgi
