CREATE FUNCTION users_create( email citext, hashed_password text, name text,
        group_name text,admin boolean default false)
RETURNS TABLE (USER_ID TEXT, EMAIL CITEXT, NAME TEXT, GROUP_NAME TEXT, ADMIN BOOLEAN, AUTH_ID TEXT, HASHED_PASSWORD TEXT, DATE_CREATED TIMESTAMP WITH TIME ZONE, DATE_MODIFIED TIMESTAMP WITH TIME ZONE)
as $$
WITH USER_INSERT_RESULT AS
            (
            INSERT INTO USERS (user_id, email, name, group_name, admin)
            VALUES ( uuid_generate_v4(), $1, $3, $4, $5)
            RETURNING user_id)
            INSERT INTO AUTH (auth_id, hashed_password, user_id)
            SELECT uuid_generate_v4(), $2, user_id FROM USER_INSERT_RESULT;

SELECT USERS.USER_ID::text, EMAIL, NAME, GROUP_NAME, ADMIN, AUTH_ID::text, HASHED_PASSWORD, DATE_CREATED, DATE_MODIFIED
FROM USERS JOIN AUTH ON USERS.USER_ID = AUTH.USER_ID
WHERE EMAIL=$1;
$$
LANGUAGE SQL;

CREATE FUNCTION users_read( user_id text )
RETURNS TABLE(USER_ID TEXT, EMAIL CITEXT, NAME TEXT, GROUP_NAME TEXT, ADMIN BOOLEAN, AUTH_ID TEXT, HASHED_PASSWORD TEXT, DATE_CREATED TIMESTAMP WITH TIME ZONE, DATE_MODIFIED TIMESTAMP WITH TIME ZONE)
as $$
SELECT USERS.USER_ID::text, EMAIL, NAME, GROUP_NAME, ADMIN, AUTH_ID::text, HASHED_PASSWORD, DATE_CREATED, DATE_MODIFIED
FROM USERS JOIN AUTH ON USERS.USER_ID = AUTH.USER_ID
WHERE USERS.USER_ID::text=$1;
$$
LANGUAGE SQL;

CREATE FUNCTION users_fetchall()
RETURNS TABLE(USER_ID TEXT, EMAIL CITEXT, NAME TEXT, GROUP_NAME TEXT, ADMIN BOOLEAN, AUTH_ID TEXT, HASHED_PASSWORD TEXT, DATE_CREATED TIMESTAMP WITH TIME ZONE, DATE_MODIFIED TIMESTAMP WITH TIME ZONE)
as $$
SELECT USERS.USER_ID::text, EMAIL, NAME, GROUP_NAME, ADMIN, AUTH_ID::text, HASHED_PASSWORD, DATE_CREATED, DATE_MODIFIED
FROM USERS JOIN AUTH ON USERS.USER_ID = AUTH.USER_ID
$$
LANGUAGE SQL;


CREATE FUNCTION users_update(user_id text, email citext, name text,
        group_name text,admin boolean, hashed_password text)
RETURNS TABLE (USER_ID TEXT, EMAIL CITEXT, NAME TEXT, GROUP_NAME TEXT, ADMIN BOOLEAN, AUTH_ID TEXT,
HASHED_PASSWORD TEXT, DATE_CREATED TIMESTAMP WITH TIME ZONE, DATE_MODIFIED TIMESTAMP WITH TIME ZONE)
as $$

UPDATE USERS
SET EMAIL=$2, NAME=$3, GROUP_NAME=$4, ADMIN=$5, DATE_MODIFIED=now()
WHERE USER_ID = CAST($1 AS UUID);

UPDATE AUTH SET HASHED_PASSWORD = $6
WHERE USER_ID = CAST($1 AS UUID);

SELECT USERS.USER_ID::text, EMAIL, NAME, GROUP_NAME, ADMIN, AUTH_ID::text, HASHED_PASSWORD, DATE_CREATED, DATE_MODIFIED
FROM USERS JOIN AUTH ON USERS.USER_ID = AUTH.USER_ID
WHERE USERS.USER_ID::text=$1;
$$
LANGUAGE SQL;
