const currentPartners = [
  {
    details: [
      ["Locations", "Multnomah County"],
      ["Income Restrictions", "Low-income only"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Free"],
    ],
    name: "Portland Community College",
    area: "Northeast Portland",
    instructions: "Contact",
    contacts: ["Leni Tupper"],
    website: "https://www.pcc.edu/clear-clinic/intake-form/",
  },
  {
    details: [
      ["Locations", "Multnomah County"],
      ["Income Restrictions", "No"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "$100/case"],
    ],
    name: "Criminals Anonymous",
    area: "East Portland",
    instructions: "Contact",
    contacts: ["hrcubbedge1776@gmail.com"],
    website: "https://www.qiu-qiulaw.com/crimanon",
  },
  {
    details: [
      ["Locations", "Portland Metro"],
      ["Income Restrictions", "None"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "$100/case"],
    ],
    name: "Qiu-Qiu Law",
    area: "Portland",
    instructions: "Check your eligibility",
    contacts: [""],
    website: "https://www.qiu-qiulaw.com/recordsponge",
  },
  {
    details: [
      ["Locations", "Portland Metro"],
      ["Income Restrictions", "Unknown"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Unknown"],
    ],
    name: "Clackamas Workforce Partnership",
    area: "Oregon City",
    instructions: "Contact",
    contacts: ["Amanda Wall"],
    website: "https://www.clackamasworkforce.org",
  },
  {
    details: [
      ["Locations", "Central Oregon"],
      ["Income Restrictions", "Unknown"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Unknown"],
    ],
    name: "Lane Public Defender Services",
    area: "Eugene",
    instructions: "Contact",
    contacts: ["Zara Lukens"],
    website: "http://www.lanepds.org",
  },
  {
    details: [
      ["Locations", "Central Oregon"],
      ["Income Restrictions", "Unknown"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Unknown"],
    ],
    name: "Redmond Housing Works",
    area: "Redmond",
    instructions: "Contact",
    contacts: ["Andy Hall"],
    website: "https://www.facebook.com/OregonHousingWorks",
  },
  {
    details: [
      ["Locations", "Jackson County"],
      ["Income Restrictions", "None"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "$100/case"]
    ],
    name: "Signs of Hope",
    area: "Medford",
    instructions: "Contact",
    contacts: ["Sarah Kolb", "hope@janekolb.com", "541-821-5577"],
    website: "https://www.janekolb.com",
  },
  {
    details: [
      ["Locations", "Southern Oregon"],
      ["Income Restrictions", "Unknown"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Unknown"],
    ],
    name: "Probation and Parole, Community Justice Center",
    area: "Medford",
    instructions: "Contact",
    contacts: ["Eric Guyer"],
    website: "https://jacksoncountyor.org/community-justice",
  },
  {
    details: [
      ["Locations", "Umatilla County"],
      ["Income Restrictions", "None"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Free"],
    ],
    name: "Pendleton Legal Aid Services of Oregon",
    area: "Pendleton",
    instructions: "Contact",
    contacts: ["Arron Guevara", "arron.guevara@lasoregon.org"],
    website: "https://www.facebook.com/pendletonlegalaid/",
  },
  {
    details: [
      ["Locations", "Southern Oregon Coast"],
      ["Income Restrictions", "None"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Free"],
    ],
    name: "Bay Area First Step",
    area: "Coos Bay",
    instructions: "Contact",
    contacts: ["Devin Bailey Wilson", "dwilson@bayareafirststep.org"],
    website: "https://bayareafirststep.org/",
  },
  {
    details: [
      ["Locations", "Central Oregon"],
      ["Income Restrictions", "None"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Free"],
    ],
    name: "Linn-Benton Community College",
    area: "Albany",
    instructions: "Contact",
    contacts: ["Drew Hastings", "hastind@linnbenton.edu"],
    website: "https://www.linnbenton.edu",
  },
  {
    details: [
      ["Locations", "Southern Oregon"],
      ["Income Restrictions", "None"],
      ["Analysis Cost", "Free"],
      ["Paperwork Cost", "Free"],
    ],
    name: "WorkSource Oregon",
    area: "Roseburg",
    instructions: "Contact",
    contacts: ["Therese Roche", "Theresa.ROCHE@employ.oregon.gov"],
    website: "https://worksourceoregon.org/",
  },
];

export default currentPartners;
