FROM recordexpungpdx/recordexpungpdx:expungeservicebase

RUN mkdir -p /var/www/logs/
COPY . /var/www/
WORKDIR /var/www/
RUN pip3 install pipenv && pipenv install --system --deploy


WORKDIR /var/www
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

CMD uwsgi --http-socket 0.0.0.0:$PORT --module expungeservice.wsgi
