FROM recordexpungpdx/recordexpungpdx:expungeservicebase

RUN mkdir -p /var/www/logs/
COPY . /var/www/
WORKDIR /var/www/
RUN pip3 install pipenv && pipenv install --system --deploy


WORKDIR /var/www
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

CMD uwsgi --socket 127.0.0.1:3031 --module expungeservice.wsgi
