FROM recordexpungpdx/recordexpungpdx:expungeservicebase

RUN python3.7 -m pip install pipenv

WORKDIR /var/www/
COPY . /var/www/
RUN pipenv install --system --deploy
RUN mkdir -p /var/www/logs/

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
CMD ["uwsgi", "--py-autoreload", "1",  "--http", "0.0.0.0:5000", "--module", "expungeservice.wsgi", "--die-on-term"]
